### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by Greg-Freeman**
Ugly, rudimentary initial commit that works.
Lack of VI icons, error handling, correct abstractions but wanted to get this out there as a starting point

### CODE REVIEW

**Comment by negentropicdev** [comment]
Please save for previous back to 2020.

Also, the recommended convention for interfaces is to not prefix with 'I' like in other languages.

**Comment by negentropicdev** [comment]
I'm also looking at it in 2023 now, some more notes:

1. I avoid the default LabVIEW template of wrapping entire subVIs in error cases. More code branches means fewer optimizations in the code and it should be up to the caller, which actually has the context of the source of the error, to decide to call the subVI or not. Fully wrapped subVIs inherently get coupled to an unknown error source's behavior. Sometimes you want functionality to run and have to do extra work in the caller to still achieve execution order control but not pass in the error. Why do extra work if you just want to run the intended behavior of a subVI anyways?
2. Library.Open is an absolute no-go on this as it prevents the library from being fully cross-platform across NI supported targets: image In general, it seems like a few of the methods you're using won't be compatible with executables either. Most of the references attained via App methods and the project-itemreferences are no-go: 
image
3. There's no reason to have the VIM which will be unusable if the library ever needed to be built into a PPL to incorporate in another project. The underlying value properties are already variants so this should just stick with variant inputs and be a normal VI.

Sorry but this implementation is a no-go and I'll be rejecting this PR. I'll be taking a pass at it tonight and will ping you once it's pushed for you to take a look at.

**Comment by Greg-Freeman** [comment]
@negentropicdev 
1. Agreed
2. Wasn't aware of the cross platform issue with library open
3. For what it's worth, I was able to get this to run in an exe (basically a similarly hacked together version of code, just without refs wrapped into classes. Didn't test it with this specific code). But I was pointing it at a ppl, opening a reference, and using the library functions on the lvlibp, which seemed to work fine. I was just attacking a narrow use case of my plugin classes living in a ppl. I assumed at some point the loading of the object could be abstracted away into different load strategies, or one thing that is completely generic (which may be what you're referring to).

Edit: didn't realize vim's can't be used in a PPL. Regardless, not sure I agree on the variant logic since it's nice to drive the type and abstract away the cast from variant back to a concrete type, and not leave the onus on the user to do that each time they access a binding.

**Comment by negentropicdev** [comment]
@Greg-Freeman

VIMs are inlined and generate new instances based on the wired-in types, which isn't something that can be done once it's built into a PPL and the source is stripped. HOWEVER, you're right I forgot about getters and convenience for getting the typed value back. Cool, we'll just leave the VIM out of any classes/libraries and it'll just be a convenience method available via palettes.

My thought was that the Binding class could be overridden to allow wrapping specific types and the base class would be entirely variant based and encapsulate the programmatic dynamic dispatch functionality. The VIM could still be used for getters and the convenience without adding inheritance but the type overrides could provide some additional type safety checks and extensibility in the future.

Re #3: I would not have expected ProjectItems to work... outside of a project. TIL!

I am curious about the design of yours and sink/source. My thought was there'd be a Binding class which basically wraps a call to a VI, either read, write, or both. Also, work for any VI that has a single control/indicator besides the class and errors wired to the connector pane. (I also have a distaste for class properties :-D). I don't get why transfers always need to happen between class instances and not just provide a means of reading/writing a value more directly.

**Comment by negentropicdev** [comment]
Here's what I was envisioning, any thoughts on the design? Running ~1.7ms-2ms which I definitely want to see if I can bring down more; I suspect it's mostly from the value property nodes. Turns out the set/get controls by index, which are supposed to be faster, only work when the VI is running?

image

**Comment by negentropicdev** [comment]
Even betterer methinks 
image

**Comment by negentropicdev** [comment]
This is the magic method that makes OOPanel work, will even follow expected child class behavior where a parent class can contain the VI
image

With inheritance:
image

**Comment by negentropicdev** [comment]
And pushed to my repo if you want to poke around and see what you like/don't like.

**Comment by Greg-Freeman** [comment]
@negentropicdev to your point about the source and sink -- it may be we had different ideas about what I was trying to solve with the library.

My goal was to basically be able to have class A with a getter, seed the private data of class B using class B's setter. Hence the source and sink. And I wanted those to be runtime configurable. So a user could come in and say I want the double from class A By calling GetXYZ, but I want to pass it into class B using SetABC.

Now if that can be done with the above as well I am all ears. Admittedly I haven't pulled and looked through it yet.

**Comment by negentropicdev** [comment]
Ahhh got it. Yeah can make that work. Will post an example of that this evening. That'll just be a utility method that accepts arrays of bindings representing the source/dest bindings and having from/to class instances.

**Comment by negentropicdev** [comment]
@Greg-Freeman How's this?
image

**Comment by negentropicdev** [comment]
Which is just a convenience loop around the single transfers
image

**Comment by Greg-Freeman** [comment]
@negentropicdev This is real nice. Thanks for the example, I couldn't see the forest through the trees. Totally forgot LabVIEW will adapt the class wires going through the SubVI to the concrete type if the compiler can deduce that. Was so caught up in using a VIM that I didn't consider other options.

Man oh man though, I do wish LabVIEW had malleable classes, generics, templates...whatever you want to call them. You could wrap all that binding stuff up in another object called "Binder" or something and have it be `Binder<Server, NetConfig>` and drive type safety throughout everything, storing all the bindings inside the Binder class private data at Binder construction time. The _binder_ would have the single responsibility of executing the _bindings_. Then you could have a method on the Binder class called Transfer and its only two inputs would be the two objects, since all the binding info would already be in the private data.

But alas, we can work with what we've got.

Edit: actually, maybe you could still do that if you created the bindings first and passed them into the binder using aggregation? Not sure, one of those things I'd just have to try since I am having trouble mapping it all out in my head

**Comment by Greg-Freeman** [comment]
What about something like this?

image

You could argue maybe it doesn't need to be in the library, and the library provides the necessary framework for someone to create it on their own like I just did. But it may be useful enough to include and kind of separates the responsibility of the binding definition into one class and then the execution of the binding into another class, the `Binder`.

**Pull request closed without merging**
